[package]
name = "perc20-on-eos"
version = "1.10.0"
authors = ["gregkapka <greg@oraclize.it>"]

[dependencies]
log = "0.4.14"
docopt = "1.1.1"
serde_derive = "1.0.125"
lib = { path = "../lib", default-features = false }
serde = { version = "1.0.125", features = ["derive"] }
